baseURL: "https://alschel.github.io/atlas-of-religions/"
publishDir: "docs"
relativeURLs: false
theme: "hugo-PaperMod"
languageCode: en-us
title: "Атлас религиозного ландшафта Тюменской области"
menu:
    main:
        - name: О проекте
          url: about
          weight: 5
        - name: Карта религиозных объединений
          url: interactive-map
          weight: 10
        - name: Тематические карты
          url: thematic-maps
          weight: 20
        - name: Публикации
          url: publications
          weight: 30
params:
    profileMode:
        enabled: true
        title: " " # optional default will be site title
        subtitle: "заменить картинку "
        imageUrl: "cover.jpg" # optional
        #imageTitle: "Ремезо" # optional
        imageWidth: 97% # custom size
        imageHeight: 90% # custom size
    # homeInfoParams:
    #     title: Атлас религиозного ландшафта Тюменской области
    #     Content: Проект поддержан
    ShowToc: false
    cover:
        linkFullImages: true

