---
pagetitle: О проекте
output:
  html_document:
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

«Ландшафт ― ключ к культуре», писал в 1979 г. П. Льюис, полагавший, что исследование повседневного культурного ландшафта является важнейшим инструментом понимания определяющих пространственных различий страны и социальных процессов, происходящих в ней. Российское социально-географическое пространство стягивается в направлении крупнейших городских центров. Крупные города ― средоточие экономической активности, фабрики культурных и социальных инноваций, узлы формирующихся агломераций, привлекающие к себе потоки трудовых мигрантов с соседних территорий. Небольшие населенные пункты на периферии и за пределами городских агломераций кажутся аутсайдерами, исключенными из этого масштабного исторического процесса, хотя время от времени влияние крупного города распространяется и на них, вторгаясь в их пределы в виде туристов, дачников и модернизированных управленческих практик. Однако действительно ли культурный ландшафт периферии столь уж статичен по сравнению с динамичной жизнью крупных городов? Насколько вообще он зависим от окружающего природного ландшафта и этнокультурных традиций его обитателей? Насколько быстро меняются их повседневные экономические практики, неотделимые от пространства? Как выглядит центро-периферийная география влияния, если посмотреть на нее не из центров, а с периферии?

**"Провоцирующие ландшафты"** - междисциплинарный проект, цель которого - исследование культурных ландшафтов периферии одного из самых динамично трансформирующихся регионов страны ― области, расположенной в зоне притяжения двух соседних агломераций ― Екатеринбургской, относящейся к числу крупнейших в России (4-е место, свыше 2 млн чел.), и Тюменской, представляющей собой феномен быстрого роста центра с высокой экономической привлекательностью (около 1 млн чел.). Это разнообразный регион, включающий в себя контрастные по уровню освоенности и расселения районы лесостепи, тайги и подтаежного леса, сочетающий районы интенсивного индустриального природопользования с очагами традиционной хозяйственной деятельности коренных народов.  Исследование строится на использовании комплекса полевых качественных методов - процессуального проживания среды и прогулок-с-проводниками [(подробнее о методах)](https://doi.org/10.20874/2071-0437-2021-54-3-21){target="_blank"}.

**Участники прокта**: [Федор Корандей](https://www.facebook.com/noctu.vigilus){target="_blank"}, [Илья Абрамов](https://www.facebook.com/ilya.abramov.927){target="_blank"}, [Михаил Агапов](https://www.facebook.com/mike.agapov){target="_blank"}, [Владимир Костомаров](https://www.facebook.com/profile.php?id=100010802830291){target="_blank"}, [Максим Черепанов](https://www.facebook.com/maximcherepanov){target="_blank"}, [Александр Шелудков](https://www.facebook.com/alexander.sheludkov){target="_blank"}. 

Исследование поддержано грантом РФФИ № 20-05-00592 А.

*<i>Иллюстрация на заглавной странице: Чертеж земли Тобольского города из книги Семена Ремезова "Чертежная книга Сибири" (1701 г.)</i>