---
pagetitle: О проекте
output:
  html_document:
    toc: false
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### О проекте 

В современном мире религия остается одним из важных способов осмысления и упорядочивания жизни людей. С одной стороны, религиозные значения, длительное время бывшие основой культур человеческих общностей, исторически вплетены в ткань современной повседневности. С другой стороны, религиозные учения продолжают осознанно восприниматься людьми, обретая значимость в качестве систем мировоззренческого ориентирования. Знания о религиозном ландшафте -- его структуре и динамике -- особенно актуальны для многокультурных регионов, как Тюменская область.

**Атлас религиозного ландшафта Тюменской области** представляет собранные в течение нескольких лет авторами проекта материалы полевых исследований, наблюдений и многочисленных интервью, анкетирования жителей и анализа документов. В этой работы впервые описана география религиозных объединений (православных, католических, протестантских, мусульманских, иудейских), культовых объектов и паломнических центров Тюменской области, дана социальная характеристика религиозных общин, показаны пространственные закономерности и пространственная динамика религиозного ландшафта региона, выделены очаги и зоны влияния религиозных центров.

[Карта религиозных объединений](https://alschel.github.io/atlas-of-religions/interactive-map/) в интерактивном режиме представляет информацию о современых религиозных организациях и группах, а также культовых объектах в Тюменской области. В разделе [Тематические карты](https://alschel.github.io/atlas-of-religions/thematic-maps/) представлены аналитические материалы по отдельным аспектам религиозного ландшафта региона. 

**Авторы проекта**:  [Максим Черепанов](https://orcid.org/0000-0003-2246-1329){target="_blank"}, [Гульнара Мавлютова](https://orcid.org/0000-0003-4459-7104){target="_blank"}, [Роман Поплавский](https://orcid.org/0000-0001-9492-0673){target="_blank"}, [Владимир Костомаров](https://orcid.org/0000-0002-8667-3809){target="_blank"}, [Александр Шелудков](https://orcid.org/0000-0001-5409-934X){target="_blank"}. 

Исследование поддержано грантом РФФИ и Тюменской области № 20-45-720004.

*<i>Иллюстрация на заглавной странице: ... (с)</i>*